name: sharaf_yabi_ecommerce
description: A new Flutter project.
publish_to: 'none' 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: 
  animations: ^2.0.2
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_iconly: ^1.0.2
  flutter_spinkit: ^5.0.0
  flutter_svg: null 
  pull_to_refresh: ^2.0.0
  http: 
  photo_view: ^0.13.0
  get: 
  get_storage: ^2.0.3
  intl: ^0.17.0
  restart_app: ^1.1.0
  share: ^2.0.4
  lint:
  shimmer:
  vibration: ^1.7.4-nullsafety.0
  flutter_launcher_icons: ^0.9.2
  lottie: ^1.2.1
  # device_preview: ^1.0.0
  # firebase_messaging: ^11.2.6
  # firebase_core:
  # flutter_local_notifications:
  # comment_tree: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appLogo/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lang/
    - assets/lottie/
    - assets/appLogo/
    - assets/emptyState/

  fonts:
    - family: Montserrat_Bold
      fonts:
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
    - family: Montserrat_SemiBold
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
    - family: Montserrat_Medium
      fonts:
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
    - family: Montserrat_Regular
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
    - family: Montserrat_Thin
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf