name: sharaf_yabi_ecommerce
description: A new Flutter project.
publish_to: 'none'
version: 1.4.0+20
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  new_version: ^0.3.0
  badges: ^2.0.2
  cached_network_image: null
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  firebase_analytics: ^9.1.0
  firebase_core: null
  firebase_messaging: ^11.2.6
  flick_video_player: null
  flutter_iconly: ^1.0.2
  flutter_local_notifications: null
  flutter_styled_toast: ^2.0.0
  get: null
  get_storage: ^2.0.3
  http: null
  lottie: ^1.2.1
  photo_view: ^0.13.0
  pull_to_refresh: ^2.0.0
  restart_app: ^1.1.0
  share: ^2.0.4
  shimmer: null
  vibration: ^1.7.4-nullsafety.0
  video_player: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/lang/
    - assets/lottie/
    - assets/appLogo/
    - assets/emptyState/

  fonts:
    - family: Montserrat_Bold
      fonts:
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
    - family: Montserrat_SemiBold
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
    - family: Montserrat_Medium
      fonts:
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
    - family: Montserrat_Regular
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
